### ISSUE TITLE
Can you support l3 level encryption?

### ISSUE THREAD

**Issue by lvzhenbo** [Frooastside/node-widevine#1]
This library only seems to support l1 when I try it, could it support l3?

**Comment by Frooastside** [comment]
it does support l3, in fact im not even sure if it does support l1, i only tested it with l3

**Comment by lvzhenbo** [comment]
But I'm using pywidevine and node-widevine at the same time and I'm getting something different
```py
    pssh = PSSH(pssh)

    device = Device(
        type_=DeviceTypes.CHROME,
        security_level=3,
        flags=None,
        private_key=Path(private_key).read_bytes(),
        client_id=Path(client_id).read_bytes()
    )

    cdm = Cdm.from_device(device)

    session_id = cdm.open()

    cdm.set_service_certificate(session_id, Cdm.common_privacy_cert)

    challenge = cdm.get_license_challenge(session_id, pssh, license_type='OFFLINE')

	with open('challenge.bin', 'wb') as f:
        f.write(challenge)
```
```js
const pssh = Buffer.from(convertToWidevinePssh(data.pssh), "base64");
  const privateKey = fs.readFileSync(data.privatekey);
  const identifierBlob = fs.readFileSync(data.clientid);

  const session = new Session({ privateKey, identifierBlob }, pssh);

	fs.writeFileSync("license.bin", session.createLicenseRequest());
```
And node-widevine is getting the wrong thing
![image](https://github.com/user-attachments/assets/ec52dcc5-398a-4db5-8c2e-036e5f32b0a2)

**Comment by Frooastside** [comment]
i contacted you on discord. There are a few differences, I set the license_type to streaming in my package automatically, you set it to offline with pywidevine. additionally only the rust version of my package supports service certificates (yet maybe?)

**Comment by Frooastside** [comment]
I made new changes and it now supports to specify LicenseType and service certificates are also supported. #6480693250f79548fc2c54c2d10efcd28b169a64

**Comment by lvzhenbo** [comment]
Thank you very much for your work, is it right now to change my code to this?
```js
const pssh = Buffer.from(convertToWidevinePssh(data.pssh), "base64");
  const privateKey = fs.readFileSync(data.privatekey);
  const identifierBlob = fs.readFileSync(data.clientid);

  const session = new Session({ privateKey, identifierBlob }, pssh);
  console.log(SERVICE_CERTIFICATE_CHALLENGE);

  const serviceCertificateResponse = await axios.post(
    licenseurl,
    Buffer.from(SERVICE_CERTIFICATE_CHALLENGE),
    {
      headers: { },
    }
  );

  const serviceCertificate = Buffer.from(serviceCertificateResponse.data);
  await session.setServiceCertificateFromMessage(serviceCertificate);

  const response = await axios.post(
    licenseurl,
    session.createLicenseRequest(LicenseType.STREAMING),
    {
      headers: { },
    }
  );

  const keys = session.parseLicense(Buffer.from(response.data));
```

**Comment by Frooastside** [comment]
i dont work with axios but i think it looks good, you can always look at the [unit test](https://github.com/Frooastside/node-widevine/blob/main/test/license.spec.ts) because i always make sure that it is functional

**Comment by lvzhenbo** [comment]
There seems to be a slight difference.
![image](https://github.com/user-attachments/assets/b8cd4fbe-0623-4765-8c49-16c96a66e051)

**Comment by Frooastside** [comment]
i fixed some other issues it should work as expected now
