### ISSUE TITLE
Add L1 Session support

### ISSUE THREAD

**Issue by ghost** [Frooastside/node-widevine#2]
I tried the extension with a L1 key, but somehow it creates a malformed session
![grafik](https://github.com/user-attachments/assets/029c6786-2646-4f10-85a5-fc13052cfe39)

Its working fine with pywidevine

**Comment by Frooastside** [comment]
I'm not sure if I can help you, I haven't really worked on the project for a while. Did you use the version from npmjs or directly from this GitHub? Unfortunately someone claimed my package on npmjs and that is quite outdated, can you contact me on discord?

**Comment by Frooastside** [comment]
the same like here
